knp_paginator:
    page_range: 5                      # брой страници, които да се показват в навигацията
    default_options:
        page_name: page                # име на параметъра за страница в URL
        sort_field_name: sort          # име на параметъра за сортиране
        sort_direction_name: direction # име на параметъра за посока на сортиране
        distinct: true                 # да се премахнат дублиращите се резултати
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'     # шаблон за пагинацията
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # шаблон за сортируемите колони 