framework:
    default_locale: bg
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - bg
        enabled: true
        paths:
            - '%kernel.project_dir%/translations'
        
parameters:
    app_locales: ['bg', 'en', 'de', 'ru'] 