# API routes (AI-enhanced endpoints)
api:
    resource:
        path: ../src/Controller/Api/
        namespace: App\Controller\Api
    type: attribute
    prefix: /api

# Homepage redirect (must be first)
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /bg
        permanent: true

# Admin routes
admin:
    resource:
        path: ../src/Controller/Admin/
        namespace: App\Controller\Admin
    type: attribute
    prefix: /admin
    defaults:
        _locale: bg

# Authentication routes
app_login:
    path: /admin/login
    controller: App\Controller\SecurityController::login
    defaults:
        _locale: bg

app_logout:
    path: /admin/logout
    controller: App\Controller\SecurityController::logout
    defaults:
        _locale: bg

# Here Maps routes
here_maps:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    exclude: '../src/Controller/Admin/|../src/Controller/SecurityController.php|../src/Controller/Public/'

# Sitemap routes (must be before localized routes)
sitemap_index:
    path: /sitemap.xml
    controller: App\Controller\SitemapController::index
    methods: [GET]

sitemap_main:
    path: /sitemap-main.xml
    controller: App\Controller\SitemapController::main
    methods: [GET]

sitemap_language:
    path: /sitemap-{_locale}.xml
    controller: App\Controller\SitemapController::language
    requirements:
        _locale: bg|en|de|ru
    methods: [GET]

sitemap_images:
    path: /sitemap-images.xml
    controller: App\Controller\SitemapController::images
    methods: [GET]

# Localized public routes
controllers:
    resource:
        path: ../src/Controller/Public/
        namespace: App\Controller\Public
    type: attribute
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: bg
    exclude: '../src/Controller/Admin/|../src/Controller/SecurityController.php'