parameters:
    locale: 'bg'
    app_locales: 'bg|en|de|ru'
    app.default_locale: 'bg'
    upload_directory: '%kernel.project_dir%/public'
    image.width: 800
    image.height: 600
    facebook_app_id: '%env(FACEBOOK_APP_ID)%'
    facebook_app_secret: '%env(FACEBOOK_APP_SECRET)%'
    facebook_page_id: '%env(FACEBOOK_PAGE_ID)%'
    facebook_page_access_token: '%env(FACEBOOK_PAGE_ACCESS_TOKEN)%'
    linkedin_access_token: '%env(LINKEDIN_ACCESS_TOKEN)%'
    linkedin_organization_id: '%env(LINKEDIN_ORGANIZATION_ID)%'
    property_expose_directory: '%kernel.project_dir%/public/uploads/properties/exposes'
    app.here_maps_api_key: '%env(HERE_MAPS_API_KEY)%'
    app.here_maps_default_lat: '%env(float:HERE_MAPS_DEFAULT_LAT)%'
    app.here_maps_default_lng: '%env(float:HERE_MAPS_DEFAULT_LNG)%'
    app.here_maps_default_zoom: '%env(int:HERE_MAPS_DEFAULT_ZOOM)%'
    app.openai_api_key: '%env(OPENAI_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Controller\Public\:
        resource: '../src/Controller/Public/'
        tags: ['controller.service_arguments']

    App\Controller\Admin\AdminController:
        arguments:
            $propertyRepository: '@App\Repository\PropertyRepository'
            $inquiryRepository: '@App\Repository\PropertyInquiryRepository'
            $blogPostRepository: '@App\Repository\BlogPostRepository'
            $userRepository: '@App\Repository\UserRepository'
            $footerSettingsRepository: '@App\Repository\FooterSettingsRepository'

    App\Service\FileUploadService:
        arguments:
            $uploadDir: '%upload_directory%'
            $imageWidth: '%image.width%'
            $imageHeight: '%image.height%'

    App\Service\PropertyService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $fileUploadService: '@App\Service\FileUploadService'
            $slugger: '@slugger'
            $uploadDir: '%upload_directory%'

    App\Controller\PropertyController:
        arguments:
            $propertyRepository: '@App\Repository\PropertyRepository'
            $paginator: '@knp_paginator'
            $entityManager: '@doctrine.orm.entity_manager'
            $connection: '@doctrine.dbal.default_connection'

    slugger:
        class: Symfony\Component\String\Slugger\AsciiSlugger
        arguments: ['%locale%']

    App\HereMaps\Config\HereMapsConfig:
        arguments:
            $config:
                api_key: '%env(HERE_MAPS_API_KEY)%'
                default_lat: '%env(float:HERE_MAPS_DEFAULT_LAT)%'
                default_lng: '%env(float:HERE_MAPS_DEFAULT_LNG)%'
                default_zoom: '%env(int:HERE_MAPS_DEFAULT_ZOOM)%'

    App\HereMaps\Services\MapService:
        arguments:
            $config: '@App\HereMaps\Config\HereMapsConfig'
            $twig: '@twig'

    App\Service\OgImageService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\AiChatbotService:
        arguments:
            $openAiApiKey: '%app.openai_api_key%'
            $aiDataService: '@App\Service\AiDataService'