parameters:
    locale: 'bg'
    app_locales: 'bg|en'
    app.default_locale: 'bg'
    upload_directory: '%kernel.project_dir%/public/uploads'
    assets_directory: '%kernel.project_dir%/public/assets'
    image.width: 800
    image.height: 600

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $uploadDir: '%upload_directory%'
            $assetsDir: '%assets_directory%'
            $imageWidth: '%image.width%'
            $imageHeight: '%image.height%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Controller\Public\:
        resource: '../src/Controller/Public/'
        tags: ['controller.service_arguments']

    App\Controller\Admin\AdminController:
        arguments:
            $propertyRepository: '@App\Repository\PropertyRepository'
            $inquiryRepository: '@App\Repository\PropertyInquiryRepository'
            $blogPostRepository: '@App\Repository\BlogPostRepository'
            $userRepository: '@App\Repository\UserRepository'
            $footerSettingsRepository: '@App\Repository\FooterSettingsRepository'

    App\Service\FileUploadService:
        arguments:
            $uploadDir: '%upload_directory%'
            $imageWidth: '%image.width%'
            $imageHeight: '%image.height%'

    App\Service\PropertyService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $fileUploadService: '@App\Service\FileUploadService'
            $slugger: '@slugger'
            $uploadDir: '%upload_directory%'

    App\Controller\PropertyController:
        arguments:
            $propertyRepository: '@App\Repository\PropertyRepository'
            $paginator: '@knp_paginator'
            $entityManager: '@doctrine.orm.entity_manager'
            $connection: '@doctrine.dbal.default_connection'

    slugger:
        class: Symfony\Component\String\Slugger\AsciiSlugger
        arguments: ['%locale%'] 