parameters:
    locale: 'bg'
    app_locales: 'bg|en'
    app.default_locale: 'bg'
    upload_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Controller\Public\:
        resource: '../src/Controller/Public/'
        tags: ['controller.service_arguments']

    App\Controller\Admin\AdminController:
        arguments:
            $propertyRepository: '@App\Repository\PropertyRepository'
            $inquiryRepository: '@App\Repository\PropertyInquiryRepository'
            $blogPostRepository: '@App\Repository\BlogPostRepository'
            $userRepository: '@App\Repository\UserRepository'

    App\Service\FileUploadService:
        arguments:
            $uploadDir: '%upload_directory%'

    App\Service\PropertyService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $fileUploadService: '@App\Service\FileUploadService'
            $slugger: '@slugger'

    slugger:
        class: Symfony\Component\String\Slugger\AsciiSlugger
        arguments: ['%locale%'] 